@startuml
left to right direction
skinparam actorStyle awesome
actor "User" as u
package Application {

package GUI as "Graphical User Interface" {
 usecase "Main menu" as UC0

 usecase "Start Ladder\ngame" as UC1
 usecase "Change\nsettings" as UC2
 usecase "Exit application" as UC3
}

usecase "Play Ladder game" as UC4

}
u --> UC0

UC0 --> UC1
UC0 --> UC2
UC0 --> UC3

UC1 --> UC4

@enduml