@startuml

skinparam {
    nodesep 20
    ranksep 10
    rectangleFontSize 36
    usecaseFontSize 20
    packageFontSize 24
    actorFontSize 35
    actorStyle awesome
    actorShadowing true
    componentShadowing true
    rectangleShadowing true
    dpi 450
}
left to right direction

actor User #lightblue

rectangle "Board Game Application" {
  package "Game selection" {
    usecase "Select Chutes and Ladders" as UC_select_chutes
    usecase "Select Ludo" as UC_select_ludo
  }

  package "Chutes and Ladders" {
    usecase "Game menu" as UC_chutes_menu

    package "Chutes and Ladders menu" as UC_chutes_menu {
        usecase "Add players" as UC_chutes_add_players
        usecase "Add bots" as UC_chutes_add_bots
        usecase "Import / export players" as UC_chutes_import_export_players
        usecase "Select game board" as UC_chutes_select_board

        usecase "Import board" as UC_chutes_import_board
        usecase "Create / edit board" as UC_chutes_create_board

        usecase "Start game" as UC_chutes_start_game
      }

      package "Chutes and Ladders game" as UC_chutes_game {
        usecase "Roll dice" as UC_chutes_roll_dice
        usecase "Roll for all players" as UC_chutes_roll_for_all_players
        usecase "Restart game" as UC_chutes_restart_game
        usecase "Quit game" as UC_chutes_quit_game
      }
  }

  package "Ludo" {
    usecase "Game menu" as UC_ludo_menu

    package "Ludo menu" as UC_ludo_menu {
        usecase "Add players" as UC_ludo_add_players
        usecase "Add bots" as UC_ludo_add_bots
        usecase "Import / export players" as UC_ludo_import_export_players
        usecase "Select game board" as UC_ludo_select_board

        usecase "Import board" as UC_ludo_import_board
        usecase "Create / edit board" as UC_ludo_create_board

        usecase "Start game" as UC_ludo_start_game
      }

      package "Ludo game" as UC_ludo_game {
        usecase "Roll dice" as UC_ludo_roll_dice
        usecase "Roll for all players" as UC_ludo_roll_for_all_players
        usecase "Restart game" as UC_ludo_restart_game
        usecase "Quit game" as UC_ludo_quit_game
      }
  }
}
User --> UC_select_chutes
User --> UC_select_ludo

UC_select_chutes --> UC_chutes_menu
UC_chutes_start_game --> UC_chutes_game

UC_select_ludo --> UC_ludo_menu
UC_ludo_start_game --> UC_ludo_game

UC_chutes_roll_dice --> UC_chutes_roll_for_all_players : include
UC_ludo_roll_dice --> UC_ludo_roll_for_all_players : include

UC_chutes_quit_game --> UC_chutes_menu
UC_ludo_quit_game --> UC_ludo_menu

@enduml